### PR TITLE
Fix some grid schedule timeslice quirks

### PR DESCRIPTION
**Pull request by rashfael**
### Show date change labels when there is a session at night

Now uses two lines and the short names for weekday and month.
Alternatively we could ellipse the weekday.

### Remove empty slices and show the gap visually

I'm not quite sure if showing just some dots is enough.

### Things not tested yet, things to improve
- datebreak at gap (should work though)
- also compress non-talk sessions like breaks?

### CODE REVIEW

**Comment by rashfael** [comment]
Datebreak at gap looks a bit weird, would be better without the `00:30`, with the dots starting directly under the date.

Alternatively "start" the day with the first session and completely drop the gap between start of day and first session?

**Comment by rixx** [comment]
Yeah, I think starting the day with the first session is pretty reasonable, and the new gap display beforehand will make it clear that there is time passing in the meantime. Otherwise looking super good, thank you! <3

**Comment by rashfael** [comment]
Date changes now look like this:


Breaks are now displayed in a single gap:

Still have to check what happens with breaks that have empty time around them.

**Comment by rixx** [comment]
Looking preeeeetty!

**Comment by rashfael** [comment]
I think I found every edge case, some breaks might look a little funny, but nothing seems to explode anymore:

**Review by rixx — APPROVED** [review]
😍

**Pull request merged**
